version: '3'
name: data-server
services: 
  express:
    build: .
    container_name: express
    restart: always
    depends_on:
      - mongodb
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT
      - MONGODB
      - PARENT_FOLDER
      - PROJECT_ID
      - CLIENT_EMAIL
      - PRIVATE_KEY
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
volumes:
  db: