version: '3'
services: 
  node-server:
    build: .
    ports:
    - "${PORT}:${PORT}"
    environment:
    - "PORT=${PORT}"
    - "MONGODB=${MONGODB}"
    - "PARENT_FOLDER=${PARENT_FOLDER}"
    - "PROJECT_ID=${PROJECT_ID}"
    - "CLIENT_EMAIL=${CLIENT_EMAIL}"
    - "PRIVATE_KEY=${PRIVATE_KEY}"
    restart: always